name: checks

on:
  pull_request:
    branches:
      - master

jobs:
  checks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: deps:install
        run: npm ci
      - name: check:lint
        run: npm run lint
      - name: check:types
        run: npm run typecheck
      - name: test
        run: npm run test:ci
